### PR TITLE
fixing queue initialization bug

### LINKED ISSUE #674: Background sync RequestQueue doesn't re-populate
The `initQueue` method calls [`.concat(idbQueue)` here](https://github.com/GoogleChrome/workbox/blob/d60bf9744dd89ecaafe80205c329225771caf0ab/packages/workbox-background-sync/src/lib/request-queue.js#L55) when it should be calling `.push(...idbQueue)`, and as a result the queue is not initialized with existing data in the store.

In addition to fixing this, we should probably also add a test covering this case. @prateekbh are you able to do this? If not I can take a look.

### PR DESCRIPTION
**Pull request by prateekbh**
R: @jeffposnick @philipwalton 

Fixes #674 

Fixes the repopulation of the list and also adds test coverage for it

### CODE REVIEW

File: packages/workbox-background-sync/test/browser/request-queue.js [hunk 1]
```diff
@@ -37,7 +37,20 @@ describe('request-queue tests', () => {
     chai.assert.isObject(queue._config);
   });
 
-  it('queueName is corrent', () =>{
+  it('initialize should re-fill the queue', async () => {
```
Comment (gauntface) [inline packages/workbox-background-sync/test/browser/request-queue.js]: I may be misunderstanding the original problem, but this test doesn't actually test what happens when you call initQueue when there are no entries to be added.

Comment (prateekbh) [inline packages/workbox-background-sync/test/browser/request-queue.js]: oh I can cover that. However earlier on reboot of sw the queue was not getting re-initialized, which this should cover now.

Comment (philipwalton) [inline packages/workbox-background-sync/test/browser/request-queue.js]: Yes, please add a test case for when `this._idbQDb.get()` resolves to a null value, as it will the first time the SW starts up.

**Comment by philipwalton** [comment]
On a slight tangent, I think part of the reason this bug came about in the first place is you need to set `this._queue` to something in the constructor, but you can't run async code there, so you initialize it to an empty array and then kick off the async task.

However, I think this is an anti-pattern because we don't know when the initialization will complete and it could lead to race conditions if you invoke another prototype method before completion.

I think a better approach would be return the promise returned by `initQueue()`, and wait for its resolution in all other methods that need to reference `this._queue`.

**Comment by gauntface** [comment]
+1 @philipwalton's comments here. You have a race condition that the external libraries can't detect or handle.

Would be good to ensure initQueue is called before other methods are used as well.

**Comment by prateekbh** [comment]
I have fixed the test cases for this scenario. For the race condition I wanted to have a quick syncup before writing the code, will probably like to do it in a separate post.

**Comment by prateekbh** [comment]
@gauntface I talked to @philipwalton about the idea of handling the race condition in a separate PR.
If its cool with you, would u want to merge this one first?

File: packages/workbox-background-sync/test/browser/request-queue.js [hunk 2]
```diff
@@ -60,7 +80,7 @@ describe('request-queue tests', () => {
 
     chai.assert(callbacks.requestWillEnqueue.calledOnce);
     chai.assert(callbacks.requestWillEnqueue.calledWith(
-        sinon.match.has('request')));
+      sinon.match.has('request')));
```
Comment (philipwalton) [inline packages/workbox-background-sync/test/browser/request-queue.js]: This indentation of 4 spaces is intentional as it's a line continuation:
https://google.github.io/styleguide/jsguide.html#formatting-indent

Comment (prateekbh) [inline packages/workbox-background-sync/test/browser/request-queue.js]: our lint doesn't catch this?

**Comment by prateekbh** [comment]
@philipwalton @gauntface, fixed the whitespaces. Can we make some eslint rule to catch what @philipwalton mentioned?

**Comment by philipwalton** [comment]
There's no built-in ESLint rule config that would catch this indentation issue. I have it on my list of rules to write, but it's very low on the list.
