### PR TITLE
Fix backslashes replacement.

### LINKED ISSUE #771: `entry.url` is using Windows separator
Hi, there.

We are trying to precache our static assets for Bootstrap in this PR: https://github.com/twbs/bootstrap/pull/23533

With `workbox-build`  v2.0.0 on Windows, I'm getting this:

```js
  {
    "url": "about\\index.html",
    "revision": "f9307e727e85be5a2a420ca9a44a4f01"
  },
```

I can just do a replace for the backslashes, but I wonder if this should happen in the first place? I know that URLs do not use backslashes but here maybe this is normal?

Thanks!

### PR DESCRIPTION
**Pull request by XhmikosR**
This resulted in backslashes in the URL entries on Windows.

R: @jeffposnick @addyosmani @gauntface

Fixes #771

### CODE REVIEW

**Comment by XhmikosR** [comment]
The AppVeyor failure seems unrelated to this change.

On a side note, I could add a test if you could give me some hints, i.e. which file the test should be, if I should just check for backslashes in `entry.url`s, etc.

**Comment by gauntface** [comment]
Thanks for this @XkhmikosR.

I'm waiting on a Windows machine to test this a little more. I'm largely curious to see if I can add some tests that "fake" windows files paths so we can test on linux for Window "style" support.

**Comment by XhmikosR** [comment]
@gauntface: you have AppVeyor so you can actually test Windows at any time https://www.appveyor.com/docs/how-to/rdp-to-build-worker/

It shouldn't be too hard to have a test for that. You could use https://nodejs.org/api/path.html#path_path_win32 or just hardcode the backslashes in a test case and just check if there are any in the output regardless of the OS.

File: packages/workbox-build/src/lib/utils/filter-files.js [hunk 1]
```diff
@@ -71,7 +70,7 @@ module.exports = (fileDetails, options) => {
   // {url, revision} objects, with path.sep replaced with /.
   const normalizedManifest = filteredFileDetails.map((fileDetails) => {
     return {
-      url: fileDetails.file.replace(path.sep, '/'),
+      url: fileDetails.file.replace(/\\/g, '/'),
```
Comment (addyosmani) [inline packages/workbox-build/src/lib/utils/filter-files.js]: Thanks for the PR, @XhmikosR! In theory this should be  addressing the issue but AppVeyor appears to currently be timing out. We'll need to wait on that before moving ahead.

@gauntface I tried to login to restart the build but don't appear to be on the AV for Workbox. Can has privs?

**Comment by addyosmani** [comment]
@gauntface Change here LGTM, but I don't have access to our AppVeyor account to follow the windows test instructions @XhmikosR linked up to. If you get a chance can you add me or test it out? Would love to see if we can unblock https://github.com/twbs/bootstrap/pull/23533

**Comment by XhmikosR** [comment]
Would be nice if we had a test to ensure this doesn't happen again in the future, though :)

**Comment by gauntface** [comment]
Gonna accept this merge and dig into a way of testing this better. Windows has been awful for a while and frankly I'm stumped on a sane way to test for it.

@addyosmani tried adding you to AppVeyor but no idea how the hell it's "teams" works

**Comment by gauntface** [comment]
Thanks again for this @XhmikosR - this will be cut in the release tomorrow.

**Comment by Lyricalz** [comment]
@gauntface thanks, can we get 2.0.1 published to npm too please

**Comment by jeffposnick** [comment]
Sorry, there were a few hiccups with the `2.0.1` release, but https://www.npmjs.com/package/workbox-build (and `workbox-cli`/`workbox-webpack-plugin`) are published.
