### PR TITLE
Address tab-related flakiness in integration tests

### LINKED ISSUE #2321: workbox-window integration test failures
I previously remember seeing these with Safari, but they're popping up with Firefox Stable as well.

See https://travis-ci.org/GoogleChrome/workbox/builds/633899787?utm_source=github_status&utm_medium=notification

```
[Workbox]: Running Integration test on test/workbox-window/integration with NODE_ENV 'dev' and browser 'Firefox Stable'
  [workbox-window]
    ✓ passes all window unit tests (14421ms)
  [workbox-window] Workbox
    register
      ✓ registers a new service worker (49ms)
      ✓ reports all events for a new SW registration (45ms)
      ✓ reports all events for an updated SW registration (70ms)
@http://localhost:3004/test/workbox-broadcast-update/static/integration.html.njk:4:22
@http://localhost:3004/test/workbox-broadcast-update/static/integration.html.njk:30:10
@http://localhost:3004/test/workbox-broadcast-update/static/integration.html.njk:31:8
Unexpected window opened: about:blank
      1) "before each" hook for "reports all events for an external SW registration"
  4 passing (18s)
  1 failing
  1) [workbox-window] Workbox
       "before each" hook for "reports all events for an external SW registration":
     NoSuchWindowError: Browsing context has been discarded
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:560:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:486:26)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

### PR DESCRIPTION
**Pull request by jeffposnick**
R: @philipwalton

I did a little digging, and I think this change fixes #2321, which was caused by a leftover tab from the `workbox-broadcast-update` test sometimes getting the focus in the middle of the `workbox-window` test suite. This adds a bit of structure around how tabs are opened and closed to hopefully prevent that.

That being said, the `workbox-window` integration test for externally triggered registrations is still skipped in Safari, because it just doesn't work. I tried doing the same process manually, and at that point, it follows the steps that should be covered in test, so I don't know if it's just a timing issue, or if there's something off about the webdriver environment with regard to service worker registrations in other Safari tabs.

In any case, I hope this PR is a still towards a bit less flakiness.

### CODE REVIEW

File: infra/testing/webdriver/windowLoaded.js [hunk 1]
```diff
@@ -17,8 +17,7 @@ const windowLoaded = async () => {
   await executeAsyncAndCatch(async (cb) => {
     const loaded = () => {
       if (!window.Workbox) {
-        const error = new Error('Workbox not yet loaded...');
-        cb({error: error.stack});
+        cb({error: `window.Workbox is undefined; location is ${location.href}`});
```
Comment (jeffposnick) [inline infra/testing/webdriver/windowLoaded.js:20]: This is what helped me realize that when the `workbox-window` tests were failing, it was because a tab navigated to the `workbox-broadcast-update` URL had the focus...

File: infra/testing/webdriver/getLastWindowHandle.js [hunk 2]
```diff
@@ -1,52 +0,0 @@
...
-const {server, webdriver} = global.__workbox;
-
-const testServerOrigin = server.getAddress();
-
-/**
- * Gets the window handle of the last opened tab.
- *
- * @return {string}
- */
-const getLastWindowHandle = async () => {
```
Comment (philipwalton) [inline infra/testing/webdriver/getLastWindowHandle.js:20]: I don't remember why I added this, but just checking that you've confirmed it's no longer needed.

**Review by philipwalton — APPROVED** [review]
LGTM with one question.

File: infra/testing/webdriver/getLastWindowHandle.js (hunk 2 above)
Comment (jeffposnick) [reply infra/testing/webdriver/getLastWindowHandle.js:20]: Yeah, `TabManager` replaces this.
